### ISSUE TITLE
Consider using Zod

### ISSUE THREAD

**Issue by oekstrand** [kasper-i/bultdatabasen#271]
You should using Zod to have runtime validation of the API responses and form validation. If you have a swagger spec, you can generate the schema from that.

**Comment by oekstrand** [comment]
https://github.com/Southclaws/supervillain can be used to create a schema if swagger is missing

**Comment by kasper-i** [comment]
Very cool! Work has started! :sunglasses:

**Comment by kasper-i** [comment]
Done! Only validating API responses so far but it seems to be working very well.

**Comment by kasper-i** [comment]
An added bonus was that timestamp strings can be automatically turned into native `Date` objects by using `z.coerce.date()` which is pretty neat! :sunglasses:

**Comment by oekstrand** [comment]
Nice! Good job! I've been trying out Zodios with openapi-zod-client to generate the api client from the swagger spec, works pretty good as longs as you remember to run the generator script every time you change the backend.
